version: 0.5.0.{build}
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- cmd: >-
    git submodule update --init --recursive

    build_all.bat
artifacts:
  - path: src/EffectFarm/bin/MonoGame/Release/EffectFarm.MonoGame.$(appveyor_build_version).nupkg
    name: EffectFarm.MonoGame.nupkg

  - path: src/EffectFarm/bin/FNA/Release/EffectFarm.FNA.$(appveyor_build_version).nupkg
    name: EffectFarm.FNA.nupkg

  - path: efc.$(appveyor_build_version).zip
    name: ZipPackage    
deploy:
  - provider: GitHub
    release: $(appveyor_build_version)
    description: $(appveyor_build_version)
    auth_token:
      secure: nIpZ5N6iQIXVV8/kK/Y6BqY4KYD+y7HYdq+vTKv+LqZBbxHE9BuEgZAHGVDvmJKh
    artifact: ZipPackage
    draft: false
    prerelease: false
    
  - provider: NuGet	
    api_key:
      secure: o02Abc+1Pg/C7FVPnbCA9i4RIakmOUcKjMBBCHDCbEhS69b+N05mV0xBe0ne2/Y4
    artifact: /.*\.nupkg/